### ISSUE TITLE
Do data visualization and cleaning

### ISSUE THREAD

**Issue by sergeivolodin** [EPFLMachineLearningTeamYoor/Project02#3]

**Comment by sergeivolodin** [comment]
Add +/- emoticons as tokens: https://en.wikipedia.org/wiki/List_of_emoticons
Add misspelling problems: something like grammarly?

**Comment by okm02** [comment]
Paper providing standard methodologies on data cleaning
https://arxiv.org/pdf/1601.06971.pdf
